version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: hatilist-memcached

    postgres:
      image: postgres:9.6-alpine
      container_name: hatilist-postgres
      working_dir: /application
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=development
        - POSTGRES_DB=hatilist

    webserver:
      image: nginx:alpine
      container_name: hatilist-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
      links:
       - php-fpm

    php-fpm:
      build:
        context: .
        dockerfile: phpdocker/php-fpm/Dockerfile
      container_name: hatilist-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

      links:
        - memcached
        - postgres