services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    HatilistBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    HatilistBundle\Infrastructure\:
        resource: '../../Infrastructure'
        public: true

    HatilistBundle\Infrastructure\Exercise\Repository\CleanItemRepository: ~

    HatilistBundle\Domain\Exercise\Repository\ItemRepository: '@HatilistBundle\Infrastructure\Exercise\Repository\CleanItemRepository'

    hatilistbundle.command_handlers.add_exercise:
        class: 'HatilistBundle\Domain\Exercise\Handlers\AddExerciseCommandHandler'
        public: true
        arguments:
          - '@HatilistBundle\Domain\Exercise\Repository\ItemRepository'
          - '@HatilistBundle\Infrastructure\UuidGeneratorImplementation'
        tags:
          - { name: tactician.handler, command: HatilistBundle\Domain\Exercise\Command\AddExerciseCommand }